globalThis.spiderShieldTerms = [
  'Araneidae',
  'Araneus diadematus',
  'arachnid',
  'arachnids',
  'Atrax robustus',
  'banana spider',
  'banana spiders',
  'black widow',
  'black widows',
  'brown recluse',
  'brown recluses',
  'cellar spider',
  'cellar spiders',
  'crab spider',
  'crab spiders',
  'Ctenidae',
  'daddy long leg',
  'daddy long legs',
  'daddy longleg',
  'daddy longlegs',
  'Dolomedes tenebrosus',
  'false widow',
  'false widows',
  'fishing spider',
  'fishing spiders',
  'four legged spider',
  'four legged spiders',
  'funnel web spider',
  'funnel web spiders',
  'garden spider',
  'garden spiders',
  'golden silk orb weaver',
  'golden silk orb weavers',
  'goliath birdeater',
  'goliath birdeaters',
  'harvestman',
  'harvestmen',
  'Heteropoda venatoria',
  'hobo spider',
  'hobo spiders',
  'house spider',
  'house spiders',
  'huntsman spider',
  'huntsman spiders',
  'jumping spider',
  'jumping spiders',
  'Lampona cylindrata',
  'Latrodectus hasselti',
  'Latrodectus mactans',
  'Loxosceles reclusa',
  'Lycosidae',
  'lynx spider',
  'lynx spiders',
  'Misumena vatia',
  'orb weaver',
  'orb weavers',
  'orbweaver',
  'orbweavers',
  'Parasteatoda tepidariorum',
  'Peucetia viridans',
  'Pholcidae',
  'Pholcus phalangioides',
  'redback spider',
  'redback spiders',
  'Salticidae',
  'Salticus scenicus',
  'scorpion',
  'scorpions',
  'Sicarius hahni',
  'six eyed sand spider',
  'six eyed sand spiders',
  'spider',
  'spiderling',
  'spiderlings',
  'spiders',
  'Sparassidae',
  'Steatoda grossa',
  'Steatoda nobilis',
  'tarantula',
  'tarantulas',
  'Theraphosidae',
  'Theraphosa blondi',
  'Thomisidae',
  'Trichonephila clavipes',
  'trapdoor spider',
  'trapdoor spiders',
  'wandering spider',
  'wandering spiders',
  'white tail spider',
  'white tail spiders',
  'wolf spider',
  'wolf spiders',
  'zebra spider',
  'zebra spiders',
];
